backend:
  name: git-gateway
  repo: maxberengaut/thecult.reviews
  branch: main # Branch to update (optional; defaults to master)

# These lines should *not* be indented
# publish_mode: editorial_workflow

media_folder: "public/images" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images" # The src attribute for uploaded media will begin with /images/uploads

site_url: https://thecult.reviews
display_url: https://thecult.reviews

# logo_url:


collections:
  - name: "Songs" # Used in routes, e.g., /admin/collections/blog
    extension: json
    format: json
    label: "Songs of the Month" # Used in the UI
    folder: "content/songs" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{title}}-{{fields.artist}}-{{month}}-{{day}}-{{year}}"
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Artist", name: "artist", widget: "string"}
      - {label: "Album", name: "album", widget: "string"}
      - {label: "Year", name: "year", widget: "string"}
      - {label: "Cover", name: "cover", widget: "image"}
      - {label: "YouTube Link", name: "yt_link", widget: "string"}

  - name: "Music"
    extension: json
    format: json
    label: "Music"
    folder: "content/music"
    create: true
    slug: "{{title}}-{{fields.artist}}-{{month}}-{{day}}-{{year}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Artist", name: "artist", widget: "string"}
      - {label: "Year", name: "year", widget: "string"}
      - {label: "Authors", name: "authors", widget: "string"}
      - {label: "Score", name: "score", widget: "number", value_type: "float"}
      - {label: "Cover", name: "cover", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "Movies"
    extension: json
    format: json
    label: "Movies"
    folder: "content/movies"
    create: true
    slug: "{{title}}-{{fields.artist}}-{{month}}-{{day}}-{{year}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Artist", name: "artist", widget: "string"}
      - {label: "Year", name: "year", widget: "string"}
      - {label: "Authors", name: "authors", widget: "string"}
      - {label: "Score", name: "score", widget: "number", value_type: "float"}
      - {label: "Cover", name: "cover", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "Art (Museums)"
    extension: json
    format: json
    label: "Art (Museums)"
    folder: "content/art"
    create: true
    slug: "{{title}}-{{fields.artist}}-{{month}}-{{day}}-{{year}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Artist", name: "artist", widget: "string"}
      - {label: "Year", name: "year", widget: "string"}
      - {label: "Authors", name: "authors", widget: "string"}
      - {label: "Score", name: "score", widget: "number", value_type: "float"}
      - {label: "Cover", name: "cover", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "Literature"
    extension: json
    format: json
    label: "Literature"
    folder: "content/literature"
    create: true
    slug: "{{title}}-{{fields.artist}}-{{month}}-{{day}}-{{year}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Artist", name: "artist", widget: "string"}
      - {label: "Year", name: "year", widget: "string"}
      - {label: "Authors", name: "authors", widget: "string"}
      - {label: "Score", name: "score", widget: "number", value_type: "float"}
      - {label: "Cover", name: "cover", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "Television"
    extension: json
    format: json
    label: "Television"
    folder: "content/tv"
    create: true
    slug: "{{title}}-{{fields.artist}}-{{month}}-{{day}}-{{year}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Artist", name: "artist", widget: "string"}
      - {label: "Year", name: "year", widget: "string"}
      - {label: "Authors", name: "authors", widget: "string"}
      - {label: "Score", name: "score", widget: "number", value_type: "float"}
      - {label: "Cover", name: "cover", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}

