backend:
  name: git-gateway
  repo: MAXBERENGAUT/thecult.reviews
  branch: main # Branch to update (optional; defaults to master)

# These lines should *not* be indented
# publish_mode: editorial_workflow

media_folder: "public/images" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images" # The src attribute for uploaded media will begin with /images/uploads

site_url: https://thecult.reviews
display_url: https://thecult.reviews

# logo_url:

collections:
  - name: "Songs" # Used in routes, e.g., /admin/collections/blog
    extension: json
    format: json
    label: "Songs of the Month" # Used in the UI
    folder: "content/songs" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{title}}-{{month}}-{{day}}-{{year}}"
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Artist", name: "artist", widget: "string" }
      - { label: "Album", name: "album", widget: "string" }
      - { label: "Year", name: "year", widget: "string" }
      - { label: "Cover", name: "cover", widget: "image" }
      - { label: "YouTube Link", name: "yt_link", widget: "string" }

  - name: "Music"
    extension: json
    format: json
    label: "Music"
    folder: "content/music"
    create: true
    slug: "{{title}}-{{month}}-{{day}}-{{year}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Artist", name: "artist", widget: "string" }
      - { label: "Album", name: "album", widget: "string" }
      - { label: "Year", name: "year", widget: "string" }

      - { label: "Author", name: "author", widget: "string" }
      - { label: "Score", name: "score", widget: "number", value_type: "float" }
      - { label: "Body", name: "body", widget: "markdown" }
      - {
          label: "Featured Images",
          name: "images",
          widget: "list",
          min: 1,
          max: 100,
          summary: "{{fields.image}}",
          field: { label: Image, name: image, widget: image },
        }

  - name: "Movies"
    extension: json
    format: json
    label: "Movies"
    folder: "content/movies"
    create: true
    slug: "{{title}}-{{month}}-{{day}}-{{year}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Production Company", name: "company", widget: "string" }
      - { label: "Year", name: "year", widget: "string" }
      - { label: "Director", name: "director", widget: "string" }
      - { label: "Screenwriter", name: "screenwriter", widget: "string" }
      - {
          label: "Novelist",
          name: "novelist",
          widget: "string",
          required: false,
        }
      - { label: "Actors", name: "actors", widget: "string" }

      - { label: "Author", name: "author", widget: "string" }
      - { label: "Score", name: "score", widget: "number", value_type: "float" }
      - { label: "Body", name: "body", widget: "markdown" }
      - {
          label: "Featured Images",
          name: "images",
          widget: "list",
          min: 1,
          max: 100,
          summary: "{{fields.image}}",
          field: { label: Image, name: image, widget: image },
        }

  - name: "Art (Museums)"
    extension: json
    format: json
    label: "Art (Museums)"
    folder: "content/art"
    create: true
    slug: "{{title}}-{{month}}-{{day}}-{{year}}"
    fields:
      - { label: "Title (Of Exhibit)", name: "title", widget: "string" }
      - { label: "Artist(s)", name: "artist", widget: "string" }
      - { label: "Year", name: "year", widget: "string" }
      - { label: "Museum", name: "museum", widget: "string" }
      - { label: "Creator", name: "creator", widget: "string" }

      - { label: "Author", name: "author", widget: "string" }
      - { label: "Score", name: "score", widget: "number", value_type: "float" }
      - { label: "Body", name: "body", widget: "markdown" }
      - {
          label: "Featured Images",
          name: "images",
          widget: "list",
          min: 1,
          max: 100,
          summary: "{{fields.image}}",
          field: { label: Image, name: image, widget: image },
        }

  - name: "Museums"
    extension: json
    format: json
    label: "Museums"
    folder: "content/museums"
    create: true
    slug: "{{title}}-{{month}}-{{day}}-{{year}}"
    fields:
      - { label: "Museum", name: "title", widget: "string" }
      - {
          label: "Featured Images",
          name: "images",
          widget: "list",
          min: 1,
          max: 100,
          summary: "{{fields.image}}",
          field: { label: Image, name: image, widget: image },
        }
      - label: "Exhibits"
        name: "exhibits"
        widget: "list"
        min: 1
        max: 100
        summary: "{{fields.exhibit}}"
        fields:
          - { label: "Title (Of Exhibit)", name: "exhibit", widget: "string" }
          - { label: "Artist(s)", name: "artist", widget: "string" }
          - { label: "Year", name: "year", widget: "string" }
          - { label: "Creator", name: "creator", widget: "string" }
          # - {label: "Floor", name: "floor", widget: "number", required: false}

          - { label: "Author", name: "author", widget: "string" }
          - {
              label: "Score",
              name: "score",
              widget: "number",
              value_type: "float",
            }
          - { label: "Body", name: "body", widget: "markdown" }
          - {
              label: "Artwork",
              name: "artwork",
              widget: "list",
              min: 1,
              max: 100,
              summary: "{{fields.image}}",
              field: { label: Image, name: image, widget: image },
            }

  - name: "Literature"
    extension: json
    format: json
    label: "Literature"
    folder: "content/literature"
    create: true
    slug: "{{title}}-{{month}}-{{day}}-{{year}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Author", name: "writer", widget: "string" }
      - { label: "Year", name: "year", widget: "string" }

      - { label: "Author", name: "author", widget: "string" }
      - { label: "Score", name: "score", widget: "number", value_type: "float" }
      - { label: "Body", name: "body", widget: "markdown" }
      - {
          label: "Featured Images",
          name: "images",
          widget: "list",
          min: 1,
          max: 100,
          summary: "{{fields.image}}",
          field: { label: Image, name: image, widget: image },
        }

  - name: "Television"
    extension: json
    format: json
    label: "Television"
    folder: "content/tv"
    create: true
    slug: "{{title}}-{{month}}-{{day}}-{{year}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Network", name: "network", widget: "string" }
      - { label: "Creator", name: "creator", widget: "string" }
      - { label: "Actors", name: "actors", widget: "string" }
      - { label: "Year", name: "year", widget: "string" }

      - { label: "Author", name: "author", widget: "string" }
      - { label: "Score", name: "score", widget: "number", value_type: "float" }
      - { label: "Body", name: "body", widget: "markdown" }
      - {
          label: "Featured Images",
          name: "images",
          widget: "list",
          min: 1,
          max: 100,
          summary: "{{fields.image}}",
          field: { label: Image, name: image, widget: image },
        }
